name: Setup SSH for EC2 instance

on:
  push:
    branches:
      - master

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
          SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
          SSH_HOST: $SSH_HOST
    # the you can run commands/scripts directly on the EC2 instance e.g.:
    - name: Create a new file on the EC2 instance with "hello-world"
      run: ssh -o StrictHostKeyChecking=no $USER_NAME@$SSH_HOST "echo "hello-world" >> new_file.txt"
